runtime: nodejs
env: flex
beta_settings:
  cloud_sql_instances: buy-and-sell-af0f4:us-west1:buy-and-sell-db
env_variables:
  DB_USER: hapi-server
  DB_PASS: hapi
  DB_NAME: buy-and-sell
  DB_SOCKET: /cloudsql/buy-and-sell-af0f4:us-west1:buy-and-sell-db